# Generated by Django 4.2.15 on 2026-04-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0004_text_operation_client_ordering'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collaborationroomevent',
            new_name='collaborati_room_id_8f3481_idx',
            old_name='collaborati_room_id_ae188f_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborationroomevent',
            new_name='collaborati_room_id_28f3c3_idx',
            old_name='collaborati_room_id_9f071f_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborationtextoperation',
            new_name='collaborati_room_id_45a2a9_idx',
            old_name='collaborati_room_id_4b8ecf_idx',
        ),
    ]
