# Generated by Django 4.2.15 on 2026-04-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaboration', '0005_rename_collaborati_room_id_ae188f_idx_collaborati_room_id_8f3481_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInferenceJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=32)),
                ('debounce_key', models.CharField(db_index=True, max_length=255)),
                ('patch_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_tier1', models.CharField(blank=True, default='', max_length=128)),
                ('model_tier2', models.CharField(blank=True, default='', max_length=128)),
                ('model_tier3', models.CharField(blank=True, default='', max_length=128)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_inference_jobs', to='collaboration.collaborationroom')),
                ('trigger_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_inference_jobs', to='collaboration.collaborationroomevent')),
            ],
        ),
        migrations.CreateModel(
            name='AIPatchSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patch_id', models.CharField(max_length=64)),
                ('centroid_x', models.IntegerField(default=0)),
                ('centroid_y', models.IntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('node_ids', models.JSONField(blank=True, default=list)),
                ('patch_hash', models.CharField(max_length=128)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_snapshots', to='ai_tasks.aiinferencejob')),
            ],
        ),
        migrations.CreateModel(
            name='AIPatchInference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier1_decision', models.BooleanField(default=False)),
                ('content_items', models.JSONField(blank=True, default=list)),
                ('local_inference', models.JSONField(blank=True, default=dict)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_inferences', to='ai_tasks.aiinferencejob')),
                ('patch_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inferences', to='ai_tasks.aipatchsnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AITaskProjectionHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_uid', models.CharField(max_length=255)),
                ('change_type', models.CharField(max_length=64)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projection_history_entries', to='ai_tasks.aiinferencejob')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_task_projection_history', to='collaboration.collaborationroom')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'created_at'], name='ai_tasks_ai_room_id_a4fcf0_idx'), models.Index(fields=['job', 'created_at'], name='ai_tasks_ai_job_id_eaf1bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AITaskProjection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_uid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('action', 'Action'), ('decision', 'Decision'), ('question', 'Question'), ('reference', 'Reference')], default='action', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='open', max_length=32)),
                ('depends_on_uids', models.JSONField(blank=True, default=list)),
                ('origin_node_ids', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projection_updates', to='ai_tasks.aiinferencejob')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_task_projections', to='collaboration.collaborationroom')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'status'], name='ai_tasks_ai_room_id_ae364f_idx'), models.Index(fields=['room', 'updated_at'], name='ai_tasks_ai_room_id_540ab2_idx')],
                'unique_together': {('room', 'task_uid')},
            },
        ),
        migrations.AddIndex(
            model_name='aipatchsnapshot',
            index=models.Index(fields=['job', 'patch_hash'], name='ai_tasks_ai_job_id_7574df_idx'),
        ),
        migrations.AddIndex(
            model_name='aipatchsnapshot',
            index=models.Index(fields=['job', 'created_at'], name='ai_tasks_ai_job_id_a2a769_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aipatchsnapshot',
            unique_together={('job', 'patch_id')},
        ),
        migrations.AddIndex(
            model_name='aiinferencejob',
            index=models.Index(fields=['room', 'status', 'created_at'], name='ai_tasks_ai_room_id_a4f061_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinferencejob',
            index=models.Index(fields=['room', 'debounce_key'], name='ai_tasks_ai_room_id_a13b31_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinferencejob',
            index=models.Index(fields=['room', 'created_at'], name='ai_tasks_ai_room_id_0222c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aiinferencejob',
            unique_together={('room', 'trigger_event')},
        ),
    ]
