"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ
from google.oauth2 import service_account

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    MOCK_EXTERNAL_SERVICES=(bool, False),
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = env("SECRET_KEY")
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")
ALLOWED_HOSTS = ["127.0.0.1", "*"]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:8000",
    "http://localhost:80",
]
# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]
LOCAL_APPS = [
    "apps.users",
    "apps.files",
    "apps.collaboration",
    "apps.ai_tasks",
]
THIRD_PARTY_APPS = [
    "rest_framework",
    "drf_yasg",
    "corsheaders",
    "celery",
    "django_celery_beat",
    "rest_framework_api_key",
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "lb_health_check.middleware.AliveCheck",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": env.db(),
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"


STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")
EMAIL_TEMPLATES_DIR = os.path.join(TEMPLATES_DIR, "emails")

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",  # Local storage
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "utils.exceptions.exception_handler.custom_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "utils.permissions.IsIamActive",
        "utils.permissions.EnforcePasswordReset",
    ],
    "DEFAULT_PAGINATION_CLASS": "utils.pagination.CorePagination",
    "PAGE_SIZE": 10,
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        # "Authorization": {"type": "apiKey", "name": "Authorization", "in": "header"},
    }
}
# API_KEY_CUSTOM_HEADER = "HTTP_EASYBRIDGE_API_KEY"
# API_KEY_CUSTOM_HEADER = "HTTP_EASYBRIDGE_API_KEY"

# Cache timeout (in seconds) - e.g., 15 minutes
CACHE_ENABLED = env.bool("CACHE_ENABLED", False)
if not CACHE_ENABLED:
    CACHE_TIMEOUT = 0
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }
else:
    CACHE_TIMEOUT = 60 * 15
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": env("REDIS_URL"),
            "TIMEOUT": CACHE_TIMEOUT,
        }
    }

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CENTRIFUGO_HMAC_SECRET = env("CENTRIFUGO_HMAC_SECRET", default="development-secret")
CENTRIFUGO_HTTP_API_KEY = env("CENTRIFUGO_HTTP_API_KEY", default="")
CENTRIFUGO_API_URL = env("CENTRIFUGO_API_URL", default="http://localhost:8100/api")
CENTRIFUGO_TOKEN_TTL_SECONDS = env.int("CENTRIFUGO_TOKEN_TTL_SECONDS", default=3600)
CENTRIFUGO_HTTP_TIMEOUT_SECONDS = env.int("CENTRIFUGO_HTTP_TIMEOUT_SECONDS", default=5)

OPENROUTER_API_KEY = env("OPENROUTER_API_KEY", default="")
OPENROUTER_BASE_URL = env("OPENROUTER_BASE_URL", default="https://openrouter.ai/api/v1")
OPENROUTER_APP_NAME = env("OPENROUTER_APP_NAME", default="LIGMA")
OPENROUTER_HTTP_REFERER = env("OPENROUTER_HTTP_REFERER", default="http://localhost:8000")

AI_TIER1_MODEL = env("AI_TIER1_MODEL", default="openrouter/auto")
AI_TIER2_MODEL = env("AI_TIER2_MODEL", default="openrouter/auto")
AI_TIER3_MODEL = env("AI_TIER3_MODEL", default="openrouter/auto")
AI_PIPELINE_ENABLED = env.bool("AI_PIPELINE_ENABLED", default=True)
AI_DEBOUNCE_MS = env.int("AI_DEBOUNCE_MS", default=1200)
AI_ROOM_COOLDOWN_MS = env.int("AI_ROOM_COOLDOWN_MS", default=3000)
AI_PATCH_THRESHOLD_X = env.int("AI_PATCH_THRESHOLD_X", default=280)
AI_PATCH_THRESHOLD_Y = env.int("AI_PATCH_THRESHOLD_Y", default=220)


# DATABASE_ROUTERS = ["utils.db.routers.DBRouter"]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",  # Apply the verbose formatter here
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # Set the desired logging level
    },
    "loggers": {
        "django.db.backends": {
            "handlers": ["console"],
            "level": "INFO",  # Set the desired logging level
            "propagate": False,
        },
        "lb_health_check": {
            "handlers": ["console"],
            "level": "WARNING",  # Ignore info logs from health check
            "propagate": False,
        },
        "__main__": {  # Add a logger for the main module
            "handlers": ["console"],
            "level": "INFO",  # Set the desired logging level
            "propagate": True,
        },
    },
}
# set the celery broker url
CELERY_BROKER_URL = env("CELERY_BROKER_URL")

# set the celery result backend
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")

# set the celery timezone
CELERY_TIMEZONE = "UTC"
DJANGO_CELERY_BEAT_TZ_AWARE = False  # TODO: need to check tz schedules


# def before_send(event, hint):
#     # Filter out health check transactions
#     if event.get("transaction") == ALIVENESS_URL:
#         return None
#     # You can filter other events here, like static file requests
#     if (
#         event.get("request", {})
#         .get("url", "")
#         .endswith(("/favicon.ico", "/robots.txt"))
#     ):
#         return None
#     return event


# if not DEBUG:
#     sentry_sdk.init(
#         environment=env("SENTRY_ENV"),
#         dsn=env("SENTRY_DNS"),
#         integrations=[DjangoIntegration()],
#         # If you wish to associate users to errors (assuming you are using
#         # django.contrib.auth) you may enable sending PII data.
#         send_default_pii=True,
#         # Set traces_sample_rate to 1.0 to capture 100%
#         # of transactions for performance monitoring.
#         # We recommend adjusting this value in production.
#         traces_sample_rate=1.0,
#         # To set a uniform sample rate
#         # Set profiles_sample_rate to 1.0 to profile 100%
#         # of sampled transactions.
#         # We recommend adjusting this value in production,
#         profiles_sample_rate=1.0,
#         before_send=before_send,
#     )

ALIVENESS_URL = "/healthcheck/"



FRONTEND_URL = env("FRONTEND_URL")


# Storage Backend Config
STORAGE_BACKEND = env.str("STORAGE_BACKEND", None)

if STORAGE_BACKEND == "azure":
    STORAGES["default"]["BACKEND"] = "storages.backends.azure_storage.AzureStorage"

    AZURE_QUERYSTRING_EXPIRE = 3600  # URL expiry time in seconds (optional)
    AZURE_OVERWRITE_FILES = False
    AZURE_ACCOUNT_NAME = env("AZURE_ACCOUNT_NAME")
    AZURE_ACCOUNT_KEY = env("AZURE_ACCOUNT_KEY")
    AZURE_CONTAINER = env("AZURE_CONTAINER")
    AZURE_SSL = env.bool("AZURE_SSL", default=True)
elif STORAGE_BACKEND == "gcs":
    GS_CREDENTIALS_PATH = env.str("GS_CREDENTIALS_PATH")
    GS_ABSOLUTE_PATH = os.path.join(BASE_DIR, GS_CREDENTIALS_PATH)
    GS_BUCKET_NAME = env.str("GS_BUCKET_NAME")
    GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
        GS_CREDENTIALS_PATH
    )
    GS_PROJECT_ID = GS_CREDENTIALS.project_id
    STORAGES["default"]["BACKEND"] = "storages.backends.gcloud.GoogleCloudStorage"
    # Optional settings
    GS_CACHE_CONTROL = "public, max-age=3600"
    # GS_DEFAULT_ACL = "publicRead"


# else:
#     STORAGES["default"]["BACKEND"] = "django.core.files.storage.FileSystemStorage"
#     AZURE_QUERYSTRING_EXPIRE = 3600  # URL expiry time in seconds (optional)
#     AZURE_OVERWRITE_FILES = False
#     AZURE_ACCOUNT_NAME = env("AZURE_ACCOUNT_NAME")
#     AZURE_ACCOUNT_KEY = env("AZURE_ACCOUNT_KEY")
#     AZURE_CONTAINER = env("AZURE_CONTAINER")
#     AZURE_SSL = env.bool("AZURE_SSL", default=True)

# this will only be true in unit tests
UNDER_TEST = False
