# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  pull_request:
    branches: ["main"]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read
jobs:
  Pre-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with black
        run: |
          black . --check

      - name: Run Ruff
        run: |
          ruff .


      - name: Test with pytest
        env:
          DEBUG: on
          SECRET_KEY: "non_secured_key"
          DATABASE_URL: "django.db.backends.sqlite3"
          EMAIL_HOST: "smtp.test.com"
          EMAIL_PORT: 587
          EMAIL_USE_SSL: "True"
          DEFAULT_FROM_EMAIL: "testing@example.com"
          FRONTEND_URL: "http://localhost:3000"
          CELERY_BROKER_URL: "memory://"
          CELERY_RESULT_BACKEND: "cache+memory://"
          CACHE_ENABLED: off
          EMAIL_HOST_USER: test@test.com
          EMAIL_HOST_PASSWORD: put_this_in_secret_in_future
          EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
          MOCK_EXTERNAL_SERVICES: on
          FACEBOOK_BASE_URL: "https://graph.facebook.com/v20.0/"
          CENTRIFUGO_TOKEN_HMAC_SECRET_KEY: "secret"
          CENTRIFUGO_API_KEY: "api_key"
          CENTRIFUGO_BASE_URL: "centrifugo"
        run: |
          pytest . --cov -vv
